version: "3"

services:
  mysql:
    container_name: agrix_db
    image: mysql:8.0.32
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agrixdb
    networks:
      - agrix_net

networks:
  agrix_net:
    driver: bridge